# Generated by Django 3.2.8 on 2021-11-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_certification_trainingmodule_usercertifications_usertraining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='TrainingModule',
        ),
        migrations.DeleteModel(
            name='UserCertifications',
        ),
        migrations.DeleteModel(
            name='UserTraining',
        ),
    ]
