# Generated by Django 3.2.8 on 2021-11-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211104_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.FloatField(max_length=12)),
                ('revision', models.CharField(max_length=1)),
                ('aircraft_model', models.FloatField(max_length=10)),
            ],
        ),
    ]
