# Generated by Django 3.2.8 on 2021-11-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211107_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='certification',
            name='level_scale',
        ),
        migrations.AddField(
            model_name='certification',
            name='level_scale',
            field=models.ManyToManyField(to='api.CertificationLevels'),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='certification_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.certification'),
        ),
        migrations.RemoveField(
            model_name='usercertifications',
            name='level',
        ),
        migrations.AddField(
            model_name='usercertifications',
            name='level',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.certificationlevels'),
            preserve_default=False,
        ),
    ]
