# Generated by Django 3.2.8 on 2021-12-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211203_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='level_scale',
        ),
        migrations.AddField(
            model_name='certification',
            name='level_scale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='part',
            field=models.FloatField(blank=True, max_length=12),
        ),
    ]
