# Generated by Django 3.2.8 on 2021-12-08 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20211204_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertifications',
            name='created_on_date',
        ),
        migrations.RemoveField(
            model_name='usercertifications',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='usercertifications',
            name='trainer',
        ),
        migrations.AddField(
            model_name='certification',
            name='days_valid',
            field=models.IntegerField(default=365),
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certification')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
