# Generated by Django 3.2.8 on 2021-12-22 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertifications',
            name='created_on_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
