# Generated by Django 3.2.8 on 2021-12-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usercertifications_created_on_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationScales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='link',
        ),
        migrations.AddField(
            model_name='usercertifications',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='null', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='CertificationLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificationscales')),
            ],
        ),
    ]
