# Generated by Django 3.2.8 on 2021-12-30 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211229_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationlevels',
            name='scale',
            field=models.ForeignKey(db_column='scale_name', on_delete=django.db.models.deletion.CASCADE, to='api.certificationscales'),
        ),
    ]
