# Generated by Django 3.2.8 on 2021-12-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_certificationlevels_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='level_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificationscales', to_field='scale_name'),
        ),
        migrations.AlterField(
            model_name='certificationlevels',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificationscales', to_field='scale_name'),
        ),
    ]
