# Generated by Django 3.2.8 on 2021-12-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211229_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationlevels',
            name='level',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usercertifications',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificationlevels', to_field='level'),
        ),
    ]
