# Generated by Django 3.2.8 on 2021-12-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211230_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='training_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.trainingmodule'),
        ),
    ]
