# Generated by Django 3.2.8 on 2021-12-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20211230_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertifications',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='api.profile'),
        ),
    ]
