# Generated by Django 3.2.8 on 2021-12-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20211230_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertraining',
            name='user_certification',
        ),
    ]
