# Generated by Django 3.2.8 on 2021-12-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_usertraining_user_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertifications',
            name='valid',
        ),
    ]
