# Generated by Django 3.2.8 on 2021-12-30 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_usercertifications_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertraining',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
            preserve_default=False,
        ),
    ]
