# Generated by Django 3.2.8 on 2022-01-04 05:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_usertraining_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='file',
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='null', null=True, upload_to='images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
