# Generated by Django 3.2.8 on 2022-01-09 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_usertraining_user_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationlevels',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.certificationscales'),
        ),
        migrations.AlterField(
            model_name='usercertifications',
            name='created_on_date',
            field=models.DateField(auto_now=True),
        ),
    ]
