# Generated by Django 3.2.8 on 2022-01-15 15:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_level_usercertifications_entered_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='null', null=True, upload_to='static/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='usercertifications',
            name='created_on_date',
            field=models.DateField(default=datetime.date(2022, 1, 15)),
        ),
        migrations.AlterUniqueTogether(
            name='usercertifications',
            unique_together={('certification_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='usertraining',
            unique_together={('user_id', 'training_id')},
        ),
    ]
