# Generated by Django 3.2.8 on 2022-01-15 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220115_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertifications',
            name='created_on_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 15, 7, 56, 1, 182798)),
        ),
    ]
