# Generated by Django 3.2.8 on 2022-01-15 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_usercertifications_created_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertifications',
            name='created_on_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 15, 8, 0, 7, 383361)),
        ),
        migrations.AlterField(
            model_name='usercertifications',
            name='entered_level',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.certificationlevels', to_field='level'),
        ),
    ]
